ansible_user: "admin"
ansible_network_os: "fortinet.fortios.fortios"
ansible_connection: "httpapi"
ansible_httpapi_use_ssl: True
ansible_httpapi_port: 443
ansible_httpapi_validate_certs: False
ansible_httpapi_session_key: {"access_token":""}